### ISSUE TITLE
Mongo Spy Issue

### ISSUE THREAD

**Issue by jclusso** [elastic/apm-agent-ruby#1034]
## Describe the bug

Seeing the following errors in our application. This happens in various different Sidekiq workers sporadically since we updated from Ruby 2.6.5 to 2.7.3.

```undefined local variable or method `type' for {"domain"=>"domain.com"}:BSON::Document```
```undefined local variable or method `type' for {"w"=>"majority"}:BSON::Document```
```undefined local variable or method `type' for {"_id"=>1}:BSON::Document```
```undefined local variable or method `type' for #<BSON::Document:0x00007fe464775880>```

## Steps to reproduce

Unable to reproduce and it sporadically happens in our Production environment.

## Expected behavior

Not throw an error.

## Environment

- **OS**: Ubuntu 18.04.5
- **Ruby version**: 2.7.3
- **Framework and version**: Rails 6.0.3.3
- **APM Server version**: 7.13.2
- **Agent version**: 4.1.0

## Additional context

```
gems/bson-4.12.0/lib/bson/binary.rb:172:in `inspect': undefined local variable or method `type' for {"w"=>"majority"}:BSON::Document (NameError)
    from gems/elastic-apm-4.1.0/lib/elastic_apm/spies/mongo.rb:106:in `inspect'
    from gems/elastic-apm-4.1.0/lib/elastic_apm/spies/mongo.rb:106:in `build_context'
    from gems/elastic-apm-4.1.0/lib/elastic_apm/spies/mongo.rb:89:in `push_event'
    from gems/elastic-apm-4.1.0/lib/elastic_apm/spies/mongo.rb:43:in `started'
    from gems/mongo-2.14.0/lib/mongo/monitoring.rb:272:in `block in started'
    from gems/mongo-2.14.0/lib/mongo/monitoring.rb:272:in `each'
    from gems/mongo-2.14.0/lib/mongo/monitoring.rb:272:in `started'
    from gems/mongo-2.14.0/lib/mongo/monitoring/publishable.rb:51:in `command_started'
    from gems/mongo-2.14.0/lib/mongo/server/connection_base.rb:157:in `block in deliver'
    from gems/mongo-2.14.0/lib/mongo/server/connection_common.rb:124:in `ensure_connected'
    from gems/mongo-2.14.0/lib/mongo/server/connection_base.rb:155:in `deliver'
    from gems/mongo-2.14.0/lib/mongo/server/connection.rb:300:in `block in deliver'
    from gems/mongo-2.14.0/lib/mongo/server/connection.rb:306:in `handle_errors'
    from gems/mongo-2.14.0/lib/mongo/server/connection.rb:299:in `deliver'
    from gems/mongo-2.14.0/lib/mongo/server/connection_base.rb:145:in `dispatch'
    from gems/mongo-2.14.0/lib/mongo/operation/shared/executable.rb:64:in `dispatch_message'
    from gems/mongo-2.14.0/lib/mongo/operation/shared/executable.rb:57:in `get_result'
    from gems/mongo-2.14.0/lib/mongo/operation/shared/executable.rb:30:in `block (3 levels) in do_execute'
    from gems/mongo-2.14.0/lib/mongo/operation/shared/response_handling.rb:96:in `add_server_diagnostics'
    from gems/mongo-2.14.0/lib/mongo/operation/shared/executable.rb:29:in `block (2 levels) in do_execute'
    from gems/mongo-2.14.0/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
    from gems/mongo-2.14.0/lib/mongo/operation/shared/executable.rb:28:in `block in do_execute'
    from gems/mongo-2.14.0/lib/mongo/operation/shared/response_handling.rb:82:in `unpin_maybe'
    from gems/mongo-2.14.0/lib/mongo/operation/shared/executable.rb:27:in `do_execute'
    from gems/mongo-2.14.0/lib/mongo/operation/shared/executable_no_validate.rb:25:in `execute'
    from gems/mongo-2.14.0/lib/mongo/operation/shared/write.rb:50:in `block in execute'
    from gems/mongo-2.14.0/lib/mongo/server/connection_pool.rb:590:in `with_connection'
    from gems/mongo-2.14.0/lib/mongo/server.rb:429:in `with_connection'
    from gems/mongo-2.14.0/lib/mongo/operation/shared/write.rb:40:in `execute'
    from gems/mongo-2.14.0/lib/mongo/collection/view/writable.rb:416:in `block (2 levels) in update_one'
    from gems/mongo-2.14.0/lib/mongo/retryable.rb:227:in `write_with_retry'
    from /usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `write_with_retry'
    from gems/mongo-2.14.0/lib/mongo/collection/view/writable.rb:403:in `block in update_one'
    from gems/mongo-2.14.0/lib/mongo/client.rb:1023:in `with_session'
    from gems/mongo-2.14.0/lib/mongo/collection/view.rb:216:in `with_session'
    from gems/mongo-2.14.0/lib/mongo/collection/view/writable.rb:397:in `update_one'
    from gems/mongoid-7.2.2/lib/mongoid/persistable.rb:324:in `persist_atomic_operations'
    from gems/mongoid-7.2.2/lib/mongoid/persistable.rb:307:in `persist_or_delay_atomic_operation'
    from gems/mongoid-7.2.2/lib/mongoid/persistable.rb:201:in `prepare_atomic_operation'
    from gems/mongoid-7.2.2/lib/mongoid/persistable/incrementable.rb:26:in `inc'
    from app/workers/REDACTED.rb:67:in `perform'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:196:in `execute_job'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
    from gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
    from gems/dogstatsd-ruby-5.0.1/lib/datadog/statsd.rb:241:in `time'
    from gems/sidekiq-pro-5.2.0/lib/sidekiq/middleware/server/statsd.rb:33:in `block in call'
    from gems/dogstatsd-ruby-5.0.1/lib/datadog/statsd.rb:318:in `batch'
    from gems/sidekiq-pro-5.2.0/lib/sidekiq/pro/metrics.rb:168:in `block in batch'
    from gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
    from gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
    from gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
    from gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
    from gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
    from gems/sidekiq-pro-5.2.0/lib/sidekiq/pro/metrics.rb:168:in `batch'
    from gems/sidekiq-pro-5.2.0/lib/sidekiq/middleware/server/statsd.rb:32:in `call'
    from gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
    from gems/elastic-apm-4.1.0/lib/elastic_apm/spies/sidekiq.rb:35:in `call'
    from gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
    from gems/bugsnag-6.10.0/lib/bugsnag/integrations/sidekiq.rb:24:in `call'
    from gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
    from gems/sidekiq-pro-5.2.0/lib/sidekiq/batch/middleware.rb:27:in `call'
    from gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
    from gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:163:in `block in process'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
    from gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:112:in `local'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
    from gems/sidekiq-6.2.1/lib/sidekiq/rails.rb:14:in `block in call'
    from gems/activesupport-6.0.3.3/lib/active_support/execution_wrapper.rb:88:in `wrap'
    from gems/activesupport-6.0.3.3/lib/active_support/reloader.rb:72:in `block in wrap'
    from gems/activesupport-6.0.3.3/lib/active_support/execution_wrapper.rb:88:in `wrap'
    from gems/activesupport-6.0.3.3/lib/active_support/reloader.rb:71:in `wrap'
    from gems/sidekiq-6.2.1/lib/sidekiq/rails.rb:13:in `call'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:257:in `stats'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
    from gems/sidekiq-6.2.1/lib/sidekiq/job_logger.rb:13:in `call'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
    from gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:79:in `global'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
    from gems/sidekiq-6.2.1/lib/sidekiq/logger.rb:11:in `with'
    from gems/sidekiq-6.2.1/lib/sidekiq/job_logger.rb:33:in `prepare'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:123:in `dispatch'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:162:in `process'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:78:in `process_one'
    from gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:68:in `run'
    from gems/sidekiq-6.2.1/lib/sidekiq/util.rb:43:in `watchdog'
    from gems/sidekiq-6.2.1/lib/sidekiq/util.rb:52:in `block in safe_thread'```

**Comment by estolfo** [comment]
Hi @jclusso, thanks for reporting this. I think the issue is actually with the bson-ruby gem. The elastic apm agent [calls `#to_s` on the mongodb command](https://github.com/elastic/apm-agent-ruby/blob/6fe414b57c23e6fbd155d9a2c1dd93a92a1891be/lib/elastic_apm/spies/mongo.rb#L106) and the bson ruby gem's `#inspect` method [here](https://github.com/mongodb/bson-ruby/blob/master/lib/bson/binary.rb#L172) cannot find the `type` reference.
Would you like to open an issue in [their issue tracker](https://jira.mongodb.org/projects/RUBY/issues/RUBY-2619?filter=allopenissues) or would you like me to?

**Comment by jclusso** [comment]
@estolfo the problem for me is there is a clearly defined type method in bson-ruby and I can't reproduce this at all. Also, I don't know what exactly `#type` is being called on. It doesn't make any sense because if you look, some of those objects look like part of the Mongoid config since it says `{"w"=>"majority"}:BSON::Document`. Can you provide any insight into what `#inspect` is being called on?

**Comment by estolfo** [comment]
To follow-up, someone just commented on the issue and said they opened the same one in the Ruby driver project. [Here](https://jira.mongodb.org/browse/RUBY-2711) it is, in case you want to follow that one too.

**Comment by jclusso** [comment]
@estolfo, @danarnold is the one who opened that issue. We work together. We'll both be following along to see how this pans out. Thank you!

**Comment by estolfo** [comment]
oh great! I didn't realize it was your colleague who opened the issue. Thanks!

**Comment by estolfo** [comment]
@danarnold and @jclusso I see that the linked issue with BSON has been closed and that they suspect it's a bug with the Ruby VM. I don't think there's anything we can do here so I'm going to close this issue.
