### ISSUE TITLE
Elastic APM Problem with Ruby 2.2.11 and Rails 3.2.22

### ISSUE THREAD

**Issue by LuanPeixotop** [elastic/apm-agent-ruby#298]
### Problem
Hi!
I have been using Elastic APM 0.4.3 in a application with ruby 2.1.5 and rails 3.2.22 perfectly.

But, after i upgrade the ruby version to 2.2.11, the elastic apm is preventing my application to start.

I tried update the elastic apm version to 0.7.4, 0.8.0 and 1.1.0 and the problem continues.
I have to take out the apm from gemfile for my application start.

the logged error it's below.

### Error
`/usr/local/rvm/gems/ruby-2.2.10/gems/activesupport-3.2.22/lib/active_support/notifications/fanout.rb:47:in `publish': NoMethodError: undefined method `call' for #<ElasticAPM::Subscriber:0x0000000234c338>: SHOW TABLES LIKE 'issue_relations' (ActiveRecord::StatementInvalid)`

**Comment by mikker** [comment]
Hi @LuanPeixotop!

The ActiveSupport::Notifications API changed from Rails 3.2 to 4.0 to no longer have a `call` method and use `start` and `finish` instead. I can't explain how this error started showing after upgrading your Ruby version.

3.2: https://github.com/rails/rails/blob/3-2-stable/activesupport/lib/active_support/log_subscriber.rb#L88
4.0 (and onwards): https://github.com/rails/rails/blob/4-0-stable/activesupport/lib/active_support/log_subscriber.rb#L78-L86

I'm sorry that Elastic APM isn't working for you anymore. Neither Ruby 2.1 nor 3.2 is supported since they both have reached their EOL.
