### ISSUE TITLE
Elasticsearch instrumentation causing undefined method error

### ISSUE THREAD

**Issue by benfb** [elastic/apm-agent-ruby#829]
## Describe the bug
After upgrading `elastic-apm` from 3.6.0 to 3.8.0, we started seeing a lot of `undefined method `config' for nil:NilClass` errors, which we traced back to this line of code: https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/spies/elasticsearch.rb#L43. 

## Steps to reproduce
There is probably an easier way to reproduce, but here's what we did which is causing the error:

1. Add the latest version of the `elastic-apm` gem to the application's Gemfile
2. Configure the `server_url`, `secret_token`, and `service_name` variables via the `config/elastic_apm.yml` file
3. Run a Sidekiq job which makes a call to elasticsearch via the `elasticsearch-api` underlying gem

## Expected behavior
The APM instrumentation should not cause an error.

## Environment
- **OS**: Linux
- **Ruby version**: 2.6.6
- **Framework and version**: Rails 6.0.2
- **APM Server version**: 7.5.0
- **Agent version**: 3.8.0

## Additional context

I tried to disable the elasticsearch instrumentation by setting `ELASTIC_APM_DISABLE_INSTRUMENTATIONS` to `['elasticsearch']`, but we still experienced the error. Is there maybe a safer way to access the APM config from the elasticsearch spy?

**Comment by mikker** [comment]
Nice debugging. I'm convinced you're correct in your assessment. Could you perhaps try with my branch from https://github.com/elastic/apm-agent-ruby/pull/830? I'll make a patch release soon.

**Comment by benfb** [comment]
@mikker That worked as far as I can tell--thanks!
