### ISSUE TITLE
Not able to log exception during startup after upgrading to 2.3.0, got undefined method `error' for nil:NilClass

### ISSUE THREAD

**Issue by n5ken** [elastic/apm-agent-ruby#305]
I got following error message after upgrade, seems we have changed the way to log error.
https://github.com/elastic/apm-agent-ruby/blob/v2.3.0/lib/elastic_apm/railtie.rb#L29-L30

```
Ryans-MacBook-Pro:saas n5ken$ rails s
Mac version is under development
=> Booting Puma
=> Rails 5.0.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
	38: from bin/rails:5:in `<main>'
	37: from bin/rails:5:in `require'
	36: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/railties-5.0.4/lib/rails/commands.rb:18:in `<top (required)>'
	35: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	34: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:85:in `server'
	33: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:85:in `tap'
	32: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	31: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/railties-5.0.4/lib/rails/commands/server.rb:102:in `start'
	30: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/railties-5.0.4/lib/rails/commands/server.rb:148:in `log_to_stdout'
	29: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
	28: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/railties-5.0.4/lib/rails/commands/server.rb:84:in `app'
	27: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
	26: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	25: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
	24: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
	23: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
	22: from /Users/n5ken/Documents/saas/config.ru:in `<main>'
	21: from /Users/n5ken/Documents/saas/config.ru:in `new'
	20: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
	19: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
	18: from /Users/n5ken/Documents/saas/config.ru:3:in `block in <main>'
	17: from /Users/n5ken/Documents/saas/config.ru:3:in `require_relative'
	16: from /Users/n5ken/Documents/saas/config/environment.rb:5:in `<top (required)>'
	15: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/railties-5.0.4/lib/rails/application.rb:352:in `initialize!'
	14: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/railties-5.0.4/lib/rails/initializable.rb:54:in `run_initializers'
	13: from /Users/n5ken/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	12: from /Users/n5ken/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	11: from /Users/n5ken/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	10: from /Users/n5ken/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
	 9: from /Users/n5ken/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
	 8: from /Users/n5ken/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	 7: from /Users/n5ken/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 6: from /Users/n5ken/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 5: from /Users/n5ken/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	 4: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/railties-5.0.4/lib/rails/initializable.rb:55:in `block in run_initializers'
	 3: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `run'
	 2: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `instance_exec'
	 1: from /Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/elastic-apm-2.3.0/lib/elastic_apm/railtie.rb:20:in `block in <class:Railtie>'
/Users/n5ken/.rvm/gems/ruby-2.5.1@happypower/gems/elastic-apm-2.3.0/lib/elastic_apm/railtie.rb:29:in `rescue in block in <class:Railtie>': undefined method `error' for nil:NilClass (NoMethodError)
```

**Comment by mikker** [comment]
Will merge asap and push a new release.
